stages:
  - test
  - build
  - release

variables:
  GIT_DEPTH: "3"
  SIMPLECOV: "true"
  RUST_BACKTRACE: "1"
  RUSTFLAGS: ""
  CARGOFLAGS: ""

.releaseable_branches:             # list of git refs for building GitLab artifacts (think "pre-release binaries")
  only:                            &releaseable_branches
    - stable
    - beta
    - tags
    - master
    - dd-sign-apk

#android-test:
#  stage: test
#  image: parity/parity-android
#  only:
#    - beta
#    - tags
#    - stable
#    - triggers
#    - master
#  script:
#    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
#    - apt-get install -y nodejs
#    - npm install -g yarn
#    - npm install
#    - npm run test
#  tags:
#    - rust 

android-build:
  stage: build
  image: parity/android-sdk
  only:
    - beta
    - tags
    - stable
    - triggers
    - master
    - dd-sign-apk
  script:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - apt-get install -y nodejs
    - echo "ndk.dir=/usr/local/android-ndk-r16b" > android/local.properties
    - echo "sdk.dir=/opt/android-sdk" >> android/local.properties
    - npm install -g yarn
    - cat android/gradle.properties
    - bash ./setup_linux.sh
    - bash ./gen_key.sh
    - cd android && ./gradlew assemble && cd ..
    - find . | grep apk
  tags:
    - rust
  artifacts:
    paths:
    - ./android/app/build/outputs/apk/release/app-release-unsigned.apk

android-release:
  stage: release
  image: parity/android-sdk
  only: *releaseable_branches
  script:
    - bash ./postinstall.sh
    - find . | grep apk
  tags:
    - rust
  artifacts:
    paths:
    - ./release/signer-app-release.apk
